/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guilibrarysystem;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author 96650
 */
public class User_Account_window extends javax.swing.JFrame {

    /**
     * Creates new form User_Account_window
     */
    public User_Account_window() {
        initComponents();
        Color backgroundColor = new Color(51,51,51);
        getContentPane().setBackground(backgroundColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        User_BD = new javax.swing.JLabel();
        Edit_Profile_Button = new javax.swing.JButton();
        User_Nationality1 = new javax.swing.JLabel();
        Logout_Button = new javax.swing.JButton();
        NameLable = new javax.swing.JLabel();
        EmailLable = new javax.swing.JLabel();
        BdLable = new javax.swing.JLabel();
        User_Sex = new javax.swing.JLabel();
        NationalityLable = new javax.swing.JLabel();
        User_Nationality = new javax.swing.JLabel();
        SexLable = new javax.swing.JLabel();
        User_Name = new javax.swing.JLabel();
        User_Email = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        back4 = new javax.swing.JLabel();

        back3.setIcon(new javax.swing.ImageIcon("C:\\Users\\reaho\\Documents\\NetBeansProjects\\GUILibrarySystem\\src\\icons\\left-arrow (2).png")); // NOI18N
        back3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back3MouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Hi Shjoon Almutairi");

        jPanel1.setBackground(java.awt.Color.white);

        User_BD.setBackground(new java.awt.Color(255, 255, 255));
        User_BD.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        User_BD.setForeground(new java.awt.Color(51, 51, 51));
        User_BD.setText("2003/6/26");
        User_BD.setToolTipText("");

        Edit_Profile_Button.setBackground(new java.awt.Color(255, 204, 153));
        Edit_Profile_Button.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Edit_Profile_Button.setText("Edit info");
        Edit_Profile_Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 153)));
        Edit_Profile_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_Profile_ButtonActionPerformed(evt);
            }
        });

        User_Nationality1.setBackground(new java.awt.Color(255, 255, 255));
        User_Nationality1.setForeground(new java.awt.Color(51, 51, 51));
        User_Nationality1.setText("User Information:");
        User_Nationality1.setToolTipText("");

        Logout_Button.setBackground(new java.awt.Color(51, 51, 51));
        Logout_Button.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Logout_Button.setForeground(new java.awt.Color(204, 204, 204));
        Logout_Button.setText("LogOut");
        Logout_Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Logout_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_ButtonActionPerformed(evt);
            }
        });

        NameLable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NameLable.setForeground(new java.awt.Color(51, 51, 51));
        NameLable.setText("Name:");

        EmailLable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmailLable.setForeground(new java.awt.Color(51, 51, 51));
        EmailLable.setText("Email:");

        BdLable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BdLable.setForeground(new java.awt.Color(51, 51, 51));
        BdLable.setText("Birthdate:");

        User_Sex.setBackground(new java.awt.Color(255, 255, 255));
        User_Sex.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        User_Sex.setForeground(new java.awt.Color(51, 51, 51));
        User_Sex.setText("Female");
        User_Sex.setToolTipText("");

        NationalityLable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NationalityLable.setForeground(new java.awt.Color(51, 51, 51));
        NationalityLable.setText("Nationality:");

        User_Nationality.setBackground(new java.awt.Color(255, 255, 255));
        User_Nationality.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        User_Nationality.setForeground(new java.awt.Color(51, 51, 51));
        User_Nationality.setText("Saudi");
        User_Nationality.setToolTipText("");

        SexLable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SexLable.setForeground(new java.awt.Color(51, 51, 51));
        SexLable.setText("Sex:");

        User_Name.setBackground(new java.awt.Color(255, 255, 255));
        User_Name.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        User_Name.setForeground(new java.awt.Color(51, 51, 51));
        User_Name.setText("Shjoon Almutairi");
        User_Name.setToolTipText("");

        User_Email.setBackground(new java.awt.Color(255, 255, 255));
        User_Email.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        User_Email.setForeground(new java.awt.Color(51, 51, 51));
        User_Email.setText("Shjoon.ns.al@gmail.com");
        User_Email.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(User_Nationality, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(User_BD, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(User_Sex, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(NationalityLable, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(User_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BdLable, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SexLable, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(User_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EmailLable, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Logout_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(User_Nationality1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Edit_Profile_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(User_Nationality1)
                    .addComponent(Edit_Profile_Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(EmailLable)
                        .addGap(4, 4, 4)
                        .addComponent(User_Email))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(NameLable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(User_Name)))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BdLable)
                    .addComponent(SexLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(User_BD)
                    .addComponent(User_Sex))
                .addGap(30, 30, 30)
                .addComponent(NationalityLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(User_Nationality)
                .addGap(18, 18, 18)
                .addComponent(Logout_Button)
                .addGap(26, 26, 26))
        );

        back4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/left-arrow (2).png"))); // NOI18N
        back4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(back4)
                        .addGap(18, 18, 18)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Edit_Profile_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_Profile_ButtonActionPerformed
        this.toBack();
        Edit_Profile GoTo_Edit_Profile = new Edit_Profile();
        GoTo_Edit_Profile.setVisible(true);
        GoTo_Edit_Profile.toFront();
    }//GEN-LAST:event_Edit_Profile_ButtonActionPerformed

    private void Logout_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_ButtonActionPerformed
        int response = JOptionPane.showConfirmDialog(null,"you will logout!","Are you sure?",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(response == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null, "Logged out successfully!");
            System.exit(0); // ===========CHANGE IT=======================
        }else{  
        }
    }//GEN-LAST:event_Logout_ButtonActionPerformed

    private void back3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_back3MouseClicked

    private void back4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back4MouseClicked
        // TODO add your handling code here:
        MainD main = new MainD();
        main.setVisible(true);
        main.pack();
        main.setLocationRelativeTo(null);//to the center
        this.dispose();
    }//GEN-LAST:event_back4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Account_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Account_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Account_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Account_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_Account_window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BdLable;
    private javax.swing.JButton Edit_Profile_Button;
    private javax.swing.JLabel EmailLable;
    private javax.swing.JButton Logout_Button;
    private javax.swing.JLabel NameLable;
    private javax.swing.JLabel NationalityLable;
    private javax.swing.JLabel SexLable;
    private javax.swing.JLabel User_BD;
    private javax.swing.JLabel User_Email;
    private javax.swing.JLabel User_Name;
    private javax.swing.JLabel User_Nationality;
    private javax.swing.JLabel User_Nationality1;
    private javax.swing.JLabel User_Sex;
    private javax.swing.JLabel back3;
    private javax.swing.JLabel back4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
